name: Deploy Element Plus on push

on:
  push:
    branches:
      - main

jobs:
  deploy-ele-ftp:
    name: Deploy Push Element Ftp
    if: github.actor != 'dependabot[bot]' && !contains(github.event.head_commit.message, '[skip ci]') && github.repository == 'vbenjs/vue-vben-admin'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Sed Config Base
        shell: bash
        run: |
          sed -i  "s#VITE_COMPRESS\\s*=.*#VITE_COMPRESS = gzip#g" ./apps/web-ele/.env.production
          sed -i  "s#VITE_PWA\\s*=.*#VITE_PWA = true#g" ./apps/web-ele/.env.production
          cat ./apps/web-ele/.env.production

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build
        run: pnpm run build:ele

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.PRO_FTP_HOST }}
          username: ${{ secrets.WEB_ELE_FTP_ACCOUNT }}
          password: ${{ secrets.WEB_ELE_FTP_PASSWORD }}
          local-dir: ./apps/web-ele/dist/

  rerun-on-failure:
    name: Rerun on failure
    needs:
      - deploy-ele-ftp
    if: failure() && fromJSON(github.run_attempt) < 10
    runs-on: ubuntu-latest
    steps:
      - name: Retry ${{ fromJSON(github.run_attempt) }} of 10
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run rerun.yml -F run_id=${{ github.run_id }}
